#!/usr/bin/env python3
"""Build the gateway's ACPI pricing dataset from the tokenix index pipeline.

The gateway prices every proxied request from a single JSON file. This script
produces that file out of what the index pipeline already writes:

  dashboard/data/prices_latest.csv  -> per-model input/output rates + scores
  dashboard/data/acpi_latest.json   -> the headline market rate

Run it after the pipeline, and sync the result to wherever the gateway mounts
`ACPI_PRICES_PATH`:

    python scripts/acpi.py                       # in the tokenix repo
    python scripts/export_prices.py              # in the tokenix repo
    python tools/export_acpi_prices.py \
        --source ../tokenix/dashboard/data \
        --out data/acpi_prices.json

A note on `acpi_score`: it is the index's **P1 intelligence-per-dollar** metric
carried through verbatim, not a rescaled 0-10 rating. Higher is better, but the
range is whatever P1's z-scoring produces, and models with no benchmark data
carry `null` rather than a made-up number.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_SOURCE = Path("../tokenix/dashboard/data")
DEFAULT_OUT = Path("data/acpi_prices.json")


def parse_optional_float(raw: object) -> float | None:
    """Empty/missing -> None (no benchmark data), distinct from a real 0.0."""
    if raw is None or str(raw).strip() == "":
        return None
    try:
        return float(raw)
    except (TypeError, ValueError):
        return None


def build(source: Path, out: Path) -> int:
    prices_csv = source / "prices_latest.csv"
    acpi_json = source / "acpi_latest.json"

    if not prices_csv.exists():
        print(
            f"Not found: {prices_csv}\n"
            f"Run `python scripts/acpi.py && python scripts/export_prices.py` "
            f"in the tokenix repo first.",
            file=sys.stderr,
        )
        return 1
    if not acpi_json.exists():
        print(f"Not found: {acpi_json}", file=sys.stderr)
        return 1

    index = json.loads(acpi_json.read_text(encoding="utf-8"))
    market_rate = index.get("acpi")
    if not market_rate:
        print(f"{acpi_json} has no `acpi` value; refusing to write.", file=sys.stderr)
        return 1

    models: dict[str, dict] = {}
    skipped = 0
    with prices_csv.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            model_id = (row.get("model_id") or "").strip().lower()
            try:
                input_rate = float(row["input_per_million_usd"])
                output_rate = float(row["output_per_million_usd"])
            except (KeyError, TypeError, ValueError):
                skipped += 1
                continue
            if not model_id or input_rate <= 0 or output_rate <= 0:
                skipped += 1
                continue

            models[model_id] = {
                "input_per_million": round(input_rate, 6),
                "output_per_million": round(output_rate, 6),
                # P1 as-is; see the module docstring.
                "acpi_score": parse_optional_float(row.get("p1")),
                "benchmark_score": parse_optional_float(row.get("benchmark_score")),
            }

    if not models:
        print("No priced models survived; refusing to write an empty dataset.", file=sys.stderr)
        return 1

    payload = {
        "_comment": (
            "Generated by tools/export_acpi_prices.py from the tokenix index "
            "pipeline. Do not hand-edit; regenerate instead."
        ),
        "last_updated": index.get("computed_at")
        or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "index": {
            "acpi_usd_per_million": market_rate,
            "weighting": index.get("weighting"),
            "model_count": index.get("model_count"),
            "provider_count": index.get("provider_count"),
            "blend": {"input_weight": 0.75, "output_weight": 0.25},
        },
        "models": models,
    }

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    scored = sum(1 for m in models.values() if m["acpi_score"] is not None)
    print(f"Wrote {out}")
    print(f"  {len(models)} models ({scored} with a P1 score), {skipped} skipped")
    print(f"  market rate: ${market_rate}/1M SCU  (as of {payload['last_updated']})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help=f"tokenix dashboard/data directory (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT, help=f"output path (default: {DEFAULT_OUT})"
    )
    args = parser.parse_args()
    return build(args.source.resolve(), args.out)


if __name__ == "__main__":
    raise SystemExit(main())
